# Site settings
title: Versioned - Headless CMS as a Service
email: info@versioned.io
description: > # this means to ignore newlines until "baseurl:"
  An admin UI and API backend that can deliver content faster and cheaper
  to your website and mobile apps. Supports custom content types with
  relationships, versioning, and publishing.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.versioned.io" # the base hostname & protocol for your site
twitter_username: versioned-cms
#github_username:  versioned
brand: Versioned
appUrl: "https://app.versioned.io"

# Build settings
markdown: kramdown
